name: Swimi
options:
  bundleIdPrefix: com.kainosk
targets:
  Swimi:
    type: framework
    platform: [iOS, macOS]
    deploymentTarget:
      iOS: "12.0"
      macOS: "11.5"
    sources: [Swimi]
    scheme:
      testTargets:
        - SwimiTests_${platform}
      gatherCoverageData: true
  SwimiTests:
    type: bundle.unit-test
    platform: [iOS, macOS]
    deploymentTarget:
      iOS: "12.0"
      macOS: "11.5"
    sources: [SwimiTests]
    dependencies:
      - target: Swimi_${platform}
      - framework: Carthage/Build/Quick.xcframework
      - framework: Carthage/Build/Nimble.xcframework
